name: PetFix
version: 1.0.0
main: eu.ansquare.petfix.Main
description: The petfix
author: SasaElele
website: https://papermc.io
api-version: 1.19
depend: [ ProtocolLib ]
commands:
 ill:
    description: Packet illusion
    usage: "Usage: /<command> [burn|glow]"